/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Events: () => import('#controllers/events_controller'),
  HeadToHead: () => import('#controllers/head_to_head_controller'),
  Home: () => import('#controllers/home_controller'),
  IdentityCorrections: () => import('#controllers/identity_corrections_controller'),
  Imports: () => import('#controllers/imports_controller'),
  LeagueCredentials: () => import('#controllers/league_credentials_controller'),
  Leagues: () => import('#controllers/leagues_controller'),
  LocationSuggestions: () => import('#controllers/location_suggestions_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  PasswordResets: () => import('#controllers/password_resets_controller'),
  PlayerMerges: () => import('#controllers/player_merges_controller'),
  Players: () => import('#controllers/players_controller'),
  Rankings: () => import('#controllers/rankings_controller'),
  Session: () => import('#controllers/session_controller'),
}
