/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthTokenSchema extends BaseModel {
  static $columns = ['consumedAt', 'createdAt', 'expiresAt', 'id', 'tokenHash', 'type', 'updatedAt', 'userId'] as const
  $columns = AuthTokenSchema.$columns
  @column.dateTime()
  declare consumedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tokenHash: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class BracketSchema extends BaseModel {
  static $columns = ['bracketType', 'createdAt', 'externalId', 'id', 'name', 'phaseId', 'updatedAt'] as const
  $columns = BracketSchema.$columns
  @column()
  declare bracketType: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare phaseId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EntrantParticipantSchema extends BaseModel {
  static $columns = ['createdAt', 'entrantId', 'id', 'platformAccountId', 'updatedAt'] as const
  $columns = EntrantParticipantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entrantId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare platformAccountId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EntrantSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'externalId', 'id', 'isDisqualified', 'name', 'placement', 'seed', 'updatedAt'] as const
  $columns = EntrantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column()
  declare externalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDisqualified: boolean
  @column()
  declare name: string
  @column()
  declare placement: number | null
  @column()
  declare seed: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventImportSchema extends BaseModel {
  static $columns = ['bracketsDone', 'bracketsTotal', 'createdAt', 'createdByUserId', 'error', 'eventId', 'finishedAt', 'id', 'leagueId', 'payload', 'platformKey', 'stage', 'stats', 'status', 'targetUrl', 'tournamentId', 'updatedAt'] as const
  $columns = EventImportSchema.$columns
  @column()
  declare bracketsDone: number
  @column()
  declare bracketsTotal: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string | null
  @column()
  declare error: string | null
  @column()
  declare eventId: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leagueId: string
  @column()
  declare payload: Record<string, any> | null
  @column()
  declare platformKey: string
  @column()
  declare stage: string | null
  @column()
  declare stats: Record<string, any>
  @column()
  declare status: string
  @column()
  declare targetUrl: string | null
  @column()
  declare tournamentId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EventSchema extends BaseModel {
  static $columns = ['capabilities', 'createdAt', 'entrantCount', 'entryKind', 'externalId', 'gameId', 'gameName', 'id', 'name', 'teamSize', 'tournamentId', 'updatedAt'] as const
  $columns = EventSchema.$columns
  @column()
  declare capabilities: Record<string, any>
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entrantCount: number | null
  @column()
  declare entryKind: string
  @column()
  declare externalId: string
  @column()
  declare gameId: string | null
  @column()
  declare gameName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare teamSize: number | null
  @column()
  declare tournamentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameCharacterSchema extends BaseModel {
  static $columns = ['createdAt', 'externalIds', 'gameId', 'id', 'name', 'updatedAt'] as const
  $columns = GameCharacterSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalIds: Record<string, any>
  @column()
  declare gameId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameStageSchema extends BaseModel {
  static $columns = ['createdAt', 'externalIds', 'gameId', 'id', 'name', 'updatedAt'] as const
  $columns = GameStageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalIds: Record<string, any>
  @column()
  declare gameId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GameSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = GameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GlobalIdentityLinkSchema extends BaseModel {
  static $columns = ['confirmedByUserId', 'createdAt', 'evidence', 'globalPlayerId', 'id', 'platformAccountId', 'source', 'updatedAt'] as const
  $columns = GlobalIdentityLinkSchema.$columns
  @column()
  declare confirmedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare evidence: Record<string, any>
  @column()
  declare globalPlayerId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare platformAccountId: string
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GlobalPlayerSchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'displayTag', 'id', 'pronouns', 'slug', 'socials', 'state', 'updatedAt'] as const
  $columns = GlobalPlayerSchema.$columns
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayTag: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare pronouns: string | null
  @column()
  declare slug: string
  @column()
  declare socials: Record<string, any>
  @column()
  declare state: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IdentityEventSchema extends BaseModel {
  static $columns = ['actorUserId', 'createdAt', 'id', 'kind', 'leagueId', 'payload'] as const
  $columns = IdentityEventSchema.$columns
  @column()
  declare actorUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare leagueId: string
  @column()
  declare payload: Record<string, any>
}

export class LeagueAdminSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leagueId', 'role', 'updatedAt', 'userId'] as const
  $columns = LeagueAdminSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leagueId: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class LeagueCredentialSchema extends BaseModel {
  static $columns = ['createdAt', 'encryptedValues', 'id', 'label', 'lastUsedAt', 'leagueId', 'platformKey', 'updatedAt'] as const
  $columns = LeagueCredentialSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare encryptedValues: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare label: string | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare leagueId: string
  @column()
  declare platformKey: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeagueEventSchema extends BaseModel {
  static $columns = ['addedByUserId', 'createdAt', 'eventId', 'id', 'leagueId', 'multiplier', 'tier', 'updatedAt'] as const
  $columns = LeagueEventSchema.$columns
  @column()
  declare addedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leagueId: string
  @column()
  declare multiplier: string | null
  @column()
  declare tier: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeagueGameSchema extends BaseModel {
  static $columns = ['createdAt', 'gameId', 'id', 'leagueId', 'updatedAt'] as const
  $columns = LeagueGameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare gameId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leagueId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeaguePlayerAccountSchema extends BaseModel {
  static $columns = ['confidence', 'confirmedByUserId', 'createdAt', 'id', 'leagueId', 'leaguePlayerId', 'platformAccountId', 'provisional', 'source', 'updatedAt'] as const
  $columns = LeaguePlayerAccountSchema.$columns
  @column()
  declare confidence: string
  @column()
  declare confirmedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leagueId: string
  @column()
  declare leaguePlayerId: string
  @column()
  declare platformAccountId: string
  @column()
  declare provisional: boolean
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeaguePlayerSchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'displayTag', 'globalPlayerId', 'id', 'lastPlayedAt', 'leagueId', 'mergedIntoId', 'pronouns', 'slug', 'socials', 'state', 'updatedAt'] as const
  $columns = LeaguePlayerSchema.$columns
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayTag: string
  @column()
  declare globalPlayerId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastPlayedAt: DateTime | null
  @column()
  declare leagueId: string
  @column()
  declare mergedIntoId: string | null
  @column()
  declare pronouns: string | null
  @column()
  declare slug: string
  @column()
  declare socials: Record<string, any>
  @column()
  declare state: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeagueSchema extends BaseModel {
  static $columns = ['correctionsVersion', 'createdAt', 'createdByUserId', 'description', 'id', 'identityVersion', 'name', 'slug', 'theme', 'timezone', 'updatedAt', 'visibility'] as const
  $columns = LeagueSchema.$columns
  @column()
  declare correctionsVersion: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: string | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identityVersion: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare theme: Record<string, any>
  @column()
  declare timezone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visibility: string
}

export class PhaseSchema extends BaseModel {
  static $columns = ['createdAt', 'eventId', 'externalId', 'id', 'name', 'order', 'updatedAt'] as const
  $columns = PhaseSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: string
  @column()
  declare externalId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare order: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PlatformAccountSchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'externalUserId', 'gamerTag', 'globalPlayerId', 'id', 'normalizedTag', 'platformKey', 'prefix', 'pronouns', 'raw', 'state', 'updatedAt', 'weakIdentity'] as const
  $columns = PlatformAccountSchema.$columns
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare externalUserId: string
  @column()
  declare gamerTag: string
  @column()
  declare globalPlayerId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare normalizedTag: string
  @column()
  declare platformKey: string
  @column()
  declare prefix: string | null
  @column()
  declare pronouns: string | null
  @column()
  declare raw: Record<string, any> | null
  @column()
  declare state: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weakIdentity: boolean
}

export class QueueJobSchema extends BaseModel {
  static $columns = ['acquiredAt', 'data', 'dedupAt', 'dedupId', 'dedupTtl', 'error', 'executeAt', 'finishedAt', 'id', 'queue', 'score', 'status', 'workerId'] as const
  $columns = QueueJobSchema.$columns
  @column()
  declare acquiredAt: bigint | number | null
  @column()
  declare data: string
  @column()
  declare dedupAt: bigint | number | null
  @column()
  declare dedupId: string | null
  @column()
  declare dedupTtl: bigint | number | null
  @column()
  declare error: string | null
  @column()
  declare executeAt: bigint | number | null
  @column()
  declare finishedAt: bigint | number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare queue: string
  @column()
  declare score: bigint | number | null
  @column()
  declare status: string
  @column()
  declare workerId: string | null
}

export class QueueScheduleSchema extends BaseModel {
  static $columns = ['createdAt', 'cronExpression', 'everyMs', 'fromDate', 'id', 'lastRunAt', 'name', 'nextRunAt', 'payload', 'runCount', 'runLimit', 'status', 'timezone', 'toDate'] as const
  $columns = QueueScheduleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cronExpression: string | null
  @column()
  declare everyMs: bigint | number | null
  @column.dateTime()
  declare fromDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastRunAt: DateTime | null
  @column()
  declare name: string
  @column.dateTime()
  declare nextRunAt: DateTime | null
  @column()
  declare payload: string
  @column()
  declare runCount: number
  @column()
  declare runLimit: number | null
  @column()
  declare status: string
  @column()
  declare timezone: string
  @column.dateTime()
  declare toDate: DateTime | null
}

export class RankingRecomputeSchema extends BaseModel {
  static $columns = ['algorithmState', 'correctionsVersion', 'createdAt', 'error', 'finishedAt', 'id', 'identityVersion', 'inputFingerprint', 'playerCount', 'rankingId', 'setCount', 'startedAt', 'status', 'updatedAt', 'watermarkAt'] as const
  $columns = RankingRecomputeSchema.$columns
  @column()
  declare algorithmState: Record<string, any> | null
  @column()
  declare correctionsVersion: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column.dateTime()
  declare finishedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identityVersion: number | null
  @column()
  declare inputFingerprint: string | null
  @column()
  declare playerCount: number
  @column()
  declare rankingId: string
  @column()
  declare setCount: number
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare watermarkAt: DateTime | null
}

export class RankingSetDeltaSchema extends BaseModel {
  static $columns = ['createdAt', 'delta', 'id', 'leaguePlayerId', 'occurredAt', 'rankingId', 'setId', 'tournamentId', 'updatedAt', 'valueAfter', 'valueBefore'] as const
  $columns = RankingSetDeltaSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delta: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leaguePlayerId: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare rankingId: string
  @column()
  declare setId: string
  @column()
  declare tournamentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare valueAfter: string
  @column()
  declare valueBefore: string
}

export class RankingStandingSchema extends BaseModel {
  static $columns = ['createdAt', 'deviation', 'eventsCounted', 'id', 'lastPlayedAt', 'leaguePlayerId', 'losses', 'metrics', 'previousRank', 'rank', 'rankingRecomputeId', 'setsPlayed', 'tournamentActivity', 'updatedAt', 'value', 'volatility', 'wins'] as const
  $columns = RankingStandingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare deviation: string | null
  @column()
  declare eventsCounted: number
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastPlayedAt: DateTime | null
  @column()
  declare leaguePlayerId: string
  @column()
  declare losses: number
  @column()
  declare metrics: Record<string, any>
  @column()
  declare previousRank: number | null
  @column()
  declare rank: number
  @column()
  declare rankingRecomputeId: string
  @column()
  declare setsPlayed: number
  @column()
  declare tournamentActivity: Record<string, any>
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
  @column()
  declare volatility: string | null
  @column()
  declare wins: number
}

export class RankingTournamentStandingSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'leaguePlayerId', 'occurredAt', 'rank', 'rankingId', 'tournamentId', 'updatedAt', 'value'] as const
  $columns = RankingTournamentStandingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare leaguePlayerId: string
  @column.dateTime()
  declare occurredAt: DateTime
  @column()
  declare rank: number
  @column()
  declare rankingId: string
  @column()
  declare tournamentId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string
}

export class RankingSchema extends BaseModel {
  static $columns = ['activityRequirements', 'algorithm', 'config', 'createdAt', 'description', 'dqPolicy', 'endsAt', 'id', 'latestRecomputeId', 'leagueId', 'name', 'published', 'recomputeMode', 'recomputeRequestedAt', 'requirements', 'slug', 'staleTournamentCount', 'startsAt', 'tournamentHashes', 'updatedAt'] as const
  $columns = RankingSchema.$columns
  @column()
  declare activityRequirements: Record<string, any>
  @column()
  declare algorithm: string
  @column()
  declare config: Record<string, any>
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare dqPolicy: string
  @column.dateTime()
  declare endsAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare latestRecomputeId: string | null
  @column()
  declare leagueId: string
  @column()
  declare name: string
  @column()
  declare published: boolean
  @column()
  declare recomputeMode: string
  @column.dateTime()
  declare recomputeRequestedAt: DateTime | null
  @column()
  declare requirements: Record<string, any>
  @column()
  declare slug: string
  @column()
  declare staleTournamentCount: number
  @column.dateTime()
  declare startsAt: DateTime | null
  @column()
  declare tournamentHashes: Record<string, any>
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class SetGameSelectionSchema extends BaseModel {
  static $columns = ['characterId', 'characterName', 'createdAt', 'entrantId', 'id', 'platformAccountId', 'setGameId', 'updatedAt'] as const
  $columns = SetGameSelectionSchema.$columns
  @column()
  declare characterId: string | null
  @column()
  declare characterName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entrantId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare platformAccountId: string | null
  @column()
  declare setGameId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SetGameSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'number', 'setId', 'stageId', 'stageName', 'updatedAt', 'winnerEntrantId'] as const
  $columns = SetGameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare number: number
  @column()
  declare setId: string
  @column()
  declare stageId: string | null
  @column()
  declare stageName: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winnerEntrantId: string | null
}

export class SetSchema extends BaseModel {
  static $columns = ['bracketId', 'completedAt', 'createdAt', 'entrantADisqualified', 'entrantAId', 'entrantBDisqualified', 'entrantBId', 'externalId', 'fullRoundText', 'id', 'identifier', 'ordinal', 'round', 'scoreA', 'scoreB', 'state', 'updatedAt', 'winnerEntrantId'] as const
  $columns = SetSchema.$columns
  @column()
  declare bracketId: string
  @column.dateTime()
  declare completedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entrantADisqualified: boolean
  @column()
  declare entrantAId: string | null
  @column()
  declare entrantBDisqualified: boolean
  @column()
  declare entrantBId: string | null
  @column()
  declare externalId: string
  @column()
  declare fullRoundText: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifier: string | null
  @column()
  declare ordinal: number | null
  @column()
  declare round: number | null
  @column()
  declare scoreA: number | null
  @column()
  declare scoreB: number | null
  @column()
  declare state: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winnerEntrantId: string | null
}

export class TournamentSchema extends BaseModel {
  static $columns = ['address', 'capabilities', 'city', 'country', 'createdAt', 'endAt', 'externalId', 'id', 'importedAt', 'isOnline', 'name', 'platformKey', 'slug', 'startAt', 'state', 'updatedAt', 'url'] as const
  $columns = TournamentSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare capabilities: Record<string, any>
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare endAt: DateTime | null
  @column()
  declare externalId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare importedAt: DateTime | null
  @column()
  declare isOnline: boolean | null
  @column()
  declare name: string
  @column()
  declare platformKey: string
  @column()
  declare slug: string
  @column.dateTime()
  declare startAt: DateTime | null
  @column()
  declare state: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare url: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isInstanceAdmin', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isInstanceAdmin: boolean
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
