import app from '@adonisjs/core/services/app'
import env from '#start/env'
import { defineConfig } from '@adonisjs/lucid'

const dbConfig = defineConfig({
  /**
   * Default connection used for all queries.
   */
  connection: 'pg',

  connections: {
    /**
     * PostgreSQL connection.
     *
     * Postgres is the only supported database. We rely on `pg_trgm` for fuzzy
     * tag matching during identity resolution, `jsonb` operators for ranking
     * configuration, and advisory locks for job concurrency, none of which
     * have portable equivalents.
     */
    pg: {
      client: 'pg',

      connection: {
        host: env.get('DB_HOST'),
        port: env.get('DB_PORT'),
        user: env.get('DB_USER'),
        password: env.get('DB_PASSWORD'),
        database: env.get('DB_DATABASE'),
      },

      migrations: {
        /**
         * Sort migration files naturally by filename.
         */
        naturalSort: true,

        /**
         * Paths containing migration files.
         */
        paths: ['database/migrations'],
      },

      /**
       * Model base classes are generated by introspecting the database after
       * every migration. Without `rulesPaths` the customisations in
       * `database/schema_rules.ts` are silently ignored, and columns Postgres
       * reports as types the introspector does not know — citext, jsonb —
       * fall back to `any`.
       */
      schemaGeneration: {
        rulesPaths: ['./database/schema_rules.ts'],
      },

      debug: app.inDev,
    },
  },
})

export default dbConfig
